# Generated by Django 5.2.12 on 2026-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskapp', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='max_quantity',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('take_out', 'Take Out'), ('dine_in', 'Dine In'), ('delivery', 'Delivery')], max_length=10),
        ),
    ]
