# Generated by Django 5.2.12 on 2026-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskapp', '0004_menuitem_max_quantity_alter_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0)),
                ('max_party_size', models.PositiveSmallIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='party_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
