# Generated by Django 5.2.12 on 2026-06-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskapp', '0007_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
